### ISSUE TITLE
Backend - Modals repeat

### ISSUE THREAD

**Issue by jaredlyon** [jaredlyon/Operation-Politibot#83]
### Modals appear to repeat their `.send` functions
No idea why this is:
<img width="675" alt="Screen Shot 2022-10-04 at 4 29 53 PM" src="https://user-images.githubusercontent.com/29807461/193920412-816e9f25-6911-40f9-a2ff-5871b65c1ddc.png">

**Comment by SirWaffleshnoz** [comment]
<img width="771" alt="Screen Shot 2022-10-04 at 6 25 31 PM" src="https://user-images.githubusercontent.com/29807461/193941402-ac0eb650-18ee-4efc-b13b-a9cd57e6831b.png">

**Comment by SirWaffleshnoz** [comment]
The problem is that users can 'cancel' out of the modal, which leaves a residual instance that gets sent alongside the real one when they *do* submit.

**Comment by jaredlyon** [comment]
Fixed in 1f85443.

**Comment by jaredlyon** [comment]
The issue has been fixed but has broken a few things down the line:
<img width="1792" alt="Screen Shot 2022-10-19 at 4 32 40 PM" src="https://user-images.githubusercontent.com/29807461/196798002-d427aded-446d-4e36-af7f-996a9ff73d8a.png">

The main issue is that the subsequent `accept` and `reject` buttons that are attached to the appeal do not send their confirmation messages back into the moderator channel, but the result *is* still DMed to the user.

**Comment by jaredlyon** [comment]
The 'undefined' issue also persists:
<img width="542" alt="Screen Shot 2022-10-26 at 4 01 28 PM" src="https://user-images.githubusercontent.com/29807461/198125256-b6a3e1d1-7230-43ed-8180-10f6a195bd4e.png">

See #93

**Comment by jaredlyon** [comment]
Fixed in 2c1df27.
