### ISSUE TITLE
Backend - Bans never send DMs even if user's DMs are open

### ISSUE THREAD

**Issue by raylou15** [jaredlyon/Operation-Politibot#86]
`ban.js` always throws its catch and fails to DM users:
<img width="882" alt="Screen Shot 2022-10-07 at 7 53 37 PM" src="https://user-images.githubusercontent.com/29807461/194676406-46a4b60f-7608-4fed-8bcc-25eb2247c800.png">

**Comment by jaredlyon** [comment]
See #91.
